### ISSUE TITLE
Fork Hydriz's scrips

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#130]
We should give some more visibility to @Hydriz 's scripts, hoping someone revamps them until he's able to work on them again: can we fork them in @WikiTeam (I can't)?
https://github.com/Hydriz/incrdumps
https://github.com/Hydriz/MediaTarballs
https://github.com/Hydriz/Dumps

**Comment by PiRSquared17** [comment]
@emijrp Can you please do this?

**Comment by Hydriz** [comment]
In fact we should generalize this to have something like a repository-creators group so that we can create more repositories for other archiving-related purposes.

**Comment by Hydriz** [comment]
Closing this. While visibility is good, i am moving them into `operations/dumps/archiving` in Gerrit in the future anyway. There isn't a need for this right now.

**Comment by nemobis** [comment]
Hydriz Scholz, 12/06/2015 20:13:
> Closing this. While visibility is good, i am moving them into
> |operations/dumps/archiving| in Gerrit in the future anyway.

Nice, thanks for the information.
