### ISSUE TITLE
Download Wikimedia dumps instead of avoidWikimediaProjects()

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#149]
When a Wikimedia-like URL is passed to dumpgenerator.py, it calls avoidWikimediaProjects(). Would it better to download the proper .7z from dumps.wikimedia.org?

**Comment by PiRSquared17** [comment]
wikipediadownloader.py exists, can this be closed? (also, should wikipediadownloader be renamed wikimediadownloader?)

**Comment by Hydriz** [comment]
I think what this means is that dumpgenerator.py should download an available dump from dumps.wikimedia.org instead of just showing an error message.

**Comment by saper** [comment]
Due to https://phabricator.wikimedia.org/T55475 I need a daily dump of a Wikimedia wiki, so I just need to use `--force`. Let's not make it too smart.

**Comment by nemobis** [comment]
Indeed, better not. Let's reopen if/when we have a clearer use case and can decide how to best handle it.
