### ISSUE TITLE
Retry with higher delay upon 503 error and others

### ISSUE THREAD

**Issue by nemobis** [WikiTeam/wikiteam#242]
python-requests handles failures automatically and retries the request, but it sometimes happens to me that I get a 503 (from Wikia) and the dump is terminated, while it would be enough to wait a few seconds. Example:

```
HTTP Error 503.
Server error, max retries exceeded.
Please resume the dump later.
http://es.gta.wikia.com/index.php
No </mediawiki> tag found: dump failed, needs fixing; resume didn't work. Exiting.
```

We could catch the ConnectionError upon 429, 503, 504 (and others?) and increase the delay, or subclass requests.Session as suggested by https://stackoverflow.com/a/23271433/4145951

**Comment by Hydriz** [comment]
Placing this under the 0.3 milestone as python-requests is a major addition for this version.

**Comment by nemobis** [comment]
> We could catch the ConnectionError upon 429, 503, 504 (and others?) and increase the delay, or subclass requests.Session as suggested by https://stackoverflow.com/a/23271433/4145951

This was done a while ago, then on how many wikis it works is another matter. :)
