### ISSUE TITLE
If the --path ends with /, strange "-2" directory gets created

### ISSUE THREAD

**Issue by saper** [WikiTeam/wikiteam#244]
I tried this one:

````
python dumpgenerator.py --xml --path /usr/home/saper/dump/exp/ --force http://pl.wikimedia.org
````

and it happily created `usr/home/saper/dump/exp/-2` directory. 

Pretty confusing, I thought some formatting function returned an error code :)

**Comment by saper** [comment]
A bit better.

The problem is not a slash per se but the assumption that `--path` should *not* exists.
Should it be named `--prefix` or something? Let's discuss in #17 .

Now I get:

https://gist.github.com/6339db1dd01561fb84a2

Btw. can we get rid of the copyright notice? I would have just pasted the output here....

**Comment by nemobis** [comment]
Marcin Cieślak, 10/04/2015 11:59:
> Now I get:
>
> https://gist.github.com/6339db1dd01561fb84a2

Your command line is wrong, unless there was a paste error. --path is 
only to be used with --resume. It seems you're actually trying to define 
the working directory?

**Comment by saper** [comment]
Ouch, didn't know this:)

**Comment by nemobis** [comment]
Marcin Cieślak, 10/04/2015 15:57:
> Ouch, didn't know this:)

Not your fault, the help is silent. If this "expected behaviour" makes 
any sense to you, I'll clarify the help; otherwise let's figure out 
something.

**Comment by saper** [comment]
I feel a bit stupid, but I just though "well I need to give source wiki and the output place, wiki can be specified on the commandline, and for the output I need --path, alright". I managed to successfully dump pl.wikimedia.org with images, so it wasn't that bad. I didn't look at the `launcher` yet and barely skimmed the code.

**Comment by PiRSquared17** [comment]
I think we should continue on #17 or another bug and let this issue be about the slash issue specifically.
