### ISSUE TITLE
Found 0 images from Bulbapedia

### ISSUE THREAD

**Issue by barryanders** [WikiTeam/wikiteam#253]
bulbapedia.bulbagarden.net/

This is awesome what you all have created here for backing up wikis. I have been using it nonstop since I found out about it. I haven't hit any snags, until when I was backing up Bulbapedia, I noticed that the images, for me, were not downloading. I just got a txt file that said END in it. Any idea what's going on? I tried finding a similar issue but didn't see one. Seems like it's common enough that there would be though.

**Comment by Hydriz** [comment]
Thanks for your interest!

There doesn't seem to be any images [on the wiki itself](http://bulbapedia.bulbagarden.net/wiki/Special:ListFiles), so it would be expected if the dumpgenerator.py fails to download any images.

I believe the script will continue working even if there are no images downloaded, so there is nothing we can do here.

**Comment by emijrp** [comment]
There are images in the wiki but embeded from other wiki.

http://bulbapedia.bulbagarden.net/wiki/File:001Bulbasaur.png

http://archives.bulbagarden.net/wiki/File:001Bulbasaur.png

Try to make a dump of http://archives.bulbagarden.net

**Comment by Hydriz** [comment]
There are no actionables here, so closing this.
