### ISSUE TITLE
Add metadata to 601 items in IA

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#255]
There is no descrpition, API, and other metadata fields for these items https://archive.org/search.php?query=wiki+uploader%3Afedericoleva+-subject%3Awikiteam

**Comment by Hydriz** [comment]
If someone is willing to make a CSV file with the appropriate metadata fields, I can help to change the metadata on the Archive automatically.

**Comment by nemobis** [comment]
Duplicate of https://github.com/WikiTeam/wikiteam/issues/209
It's certainly not worth making a CSV manually, uploader.py must be used to fix it.
