### ISSUE TITLE
File "dumpgenerator.py", line 46

### ISSUE THREAD

**Issue by robkam** [WikiTeam/wikiteam#278]
I have a MediaWiki	1.24.2 wiki to backup. When I try to use dumpgenerator.py it fails with this message:
```
File "dumpgenerator.py", line 46
    print 'Sleeping... %d seconds...' % (config['delay'])
                                    ^
SyntaxError: invalid syntax
```

**Comment by emijrp** [comment]
Are you using Python3? This version of the script works better in Python 2
I guess.

We are working on a Python 3 version but it isn't ready yet.

2016-08-15 12:10 GMT+02:00 Rob Kam <notifications@github.com>:

**Comment by robkam** [comment]
Yes Python 3.4.3

**Comment by emijrp** [comment]
Try this: python2 dumpgenerator.py

2016-08-15 14:55 GMT+02:00 Rob Kam <notifications@github.com>:

**Comment by robkam** [comment]
Thanks, it works fine with Python 2.7.12
