### ISSUE TITLE
Dumpgenerator.py to include missing pages

### ISSUE THREAD

**Issue by AdaptiveAlchemist** [WikiTeam/wikiteam#282]
Is it possible to add a function so it output's a list of pages that are missing and were not downloaded?  I use this software often and i have pages missing. If I have a list of which pages failed I can download them with special:Export.

**Comment by emijrp** [comment]
It is usually saved in the errors log. Can you see it?

**Comment by Analyst1996** [comment]
No. I know that. I am saying that some pages are missing from the dump and from the list of pages downloaded. The error log you are talking about is different. If i know which pages went missing when downloading the dump i can download them seperately. Thanks

**Comment by Analyst1996** [comment]
emijrp

**Comment by Analyst1996** [comment]
@emijrp see usually it probably happenes with only very large wikis. The wiki i am talking about has over thirty thousand pages.

**Comment by Analyst1996** [comment]
Hey bro. Just a question. I was actually talking about the pages that
fail because of insufficient ram. If i add a delay will it be solved?
I am talking about large or very large wiki like naruto or
allthetroopes . Thanks.

**Comment by nemobis** [comment]
> Hey bro. Just a question. I was actually talking about the pages that
> fail because of insufficient ram.

As was explained elsewhere, the usual workaround has been to download those manually with Special:Export on a browser. The current solution is to use the API and limit the size of the responses, which is mostly solved by using the command line option `--xmlrevisions`: please test it!
https://github.com/WikiTeam/wikiteam/issues/311
https://github.com/WikiTeam/wikiteam/issues/18
