### ISSUE TITLE
manual publishing docs mention "identifier" but there is no identifier field.

### ISSUE THREAD

**Issue by ian-kelling** [WikiTeam/wikiteam#290]
It seems that it should say this is for "Page URL" field.

**Comment by nemobis** [comment]
Are you talking about the new web upload?

**Comment by ian-kelling** [comment]
> Are you talking about the new web upload?

Oops, I should have been more specific.

https://github.com/WikiTeam/wikiteam/wiki/Tutorial#Manual_publishing

**Comment by nemobis** [comment]
Yes, I mean the HTML5 uploader at https://archive.org/upload/ , I still 
call it "new" :D https://archive.org/post/553583/new-beta-uploader

Let me update the wiki page.
