### ISSUE TITLE
KeyError: query on kiwki.us

### ISSUE THREAD

**Issue by revi** [WikiTeam/wikiteam#295]
Full log [here](https://gist.github.com/revi/46520a81e5a797b3322ea4f830531b5c).
```
  File "dumpgenerator.py", line 2084, in <module>
    main()
  File "dumpgenerator.py", line 2076, in main
    createNewDump(config=config, other=other)
  File "dumpgenerator.py", line 1649, in createNewDump
    getPageTitles(config=config, session=other['session'])
  File "dumpgenerator.py", line 403, in getPageTitles
    for title in titles:
  File "dumpgenerator.py", line 277, in getPageTitlesAPI
    allpages = jsontitles['query']['allpages']
KeyError: 'query'
```
ApiSandbox mimic'ing action=query list=allpages [works well](https://kiwki.us/wiki/%ED%8A%B9%EC%88%98:ApiSandbox#action=query&format=json&curtimestamp=1&prop=&list=allpages&utf8=1).

The site is announced to shut down their sites by 2017-05-31 15:00 UTC, so you are free to close them if it's too late. :P

**Comment by SgtLion** [comment]
I'm having this exact same bug. Is there any further understanding on it?

**Comment by nemobis** [comment]
If https://wikiapiary.com/wiki/%ED%82%A4%EC%9C%84%EC%9C%84%ED%82%A4 is right, this was a MediaWiki 1.27.1 wiki, so hardly an old one. The syntax is correct, because the first 18 namespaces worked. What was wrong with the other?

We could catch the KeyError but only if we know what to do. @SgtLion , what's the wiki you have this problem with?

**Comment by SgtLion** [comment]
The wiki in question was https://dandwiki.com . If memory serves, I think I ended up getting around the error by specifying certain namespaces and/or manually editing the list that was generated.

**Comment by nemobis** [comment]
SgtLion, 20/05/2018 22:41:
> The wiki in question was https://dandwiki.com . If memory serves, I 
> think I ended up getting around the error by specifying certain 
> namespaces and/or manually editing the list that was generated.

If this is the D&D wiki I have in mind, it is in my top 5 list of the 
most painful to archive. IIRC it had a user talk page whose history 
alone was in the tens of GiB.

After I'm done with the current round of "easy" wikis, I plan to test 
master with those worst case scenarios. Thank you for mentioning.

**Comment by SgtLion** [comment]
That sounds quite possible, in fairness. I did find a way to archive it in the end, though I think it was through other means. As a current admin on that wiki, let me know if I can be of any help with sorting out the problem cases~
