### ISSUE TITLE
Include an option in dumpgenerator.py to skip talk and user pages

### ISSUE THREAD

**Issue by fattredd** [WikiTeam/wikiteam#297]
95% of the time I don't want that anyhow, and they can account for a LOT of pages.

**Comment by nemobis** [comment]
Thanks for your suggestion and sorry for the slow reply. Have you considered the `--namespaces` command line option? You can restrict the dump to namespace 0, or that plus templates, or whatever you want.

**Comment by nemobis** [comment]
Please use the `--exnamespaces` option. You can see the IDs in the initial phase of the download (title listing) or on https://www.mediawiki.org/wiki/Manual:Namespace for the standard namespace.

Thank you!
