### ISSUE TITLE
An error have occurred while retrieving "Main_Page"

### ISSUE THREAD

**Issue by MunichCode** [WikiTeam/wikiteam#318]
Does anyone has a hint, why I always get the "An error have occurred while retrieving "Main_Page"" error when trying to dump http://en.wikishia.net/? 

Checking api.php...
api.php is OK
Checking index.php...
index.php is OK
Analysing http://en.wikishia.net/api.php
Trying generating a new dump into a new directory...
Loading page titles from namespaces = all
Excluding titles from namespaces = None
25 namespaces found
    Retrieving titles in the namespace 0
.    500 titles retrieved in the namespace 0
    Retrieving titles in the namespace 1
.    103 titles retrieved in the namespace 1
    Retrieving titles in the namespace 2
.    500 titles retrieved in the namespace 2
    Retrieving titles in the namespace 3
.    34 titles retrieved in the namespace 3
    Retrieving titles in the namespace 4
.    357 titles retrieved in the namespace 4
    Retrieving titles in the namespace 5
.    9 titles retrieved in the namespace 5
    Retrieving titles in the namespace 6
.    500 titles retrieved in the namespace 6
    Retrieving titles in the namespace 7
.    0 titles retrieved in the namespace 7
    Retrieving titles in the namespace 8
.    212 titles retrieved in the namespace 8
    Retrieving titles in the namespace 9
.    0 titles retrieved in the namespace 9
    Retrieving titles in the namespace 10
.    500 titles retrieved in the namespace 10
    Retrieving titles in the namespace 11
.    102 titles retrieved in the namespace 11
    Retrieving titles in the namespace 12
.    0 titles retrieved in the namespace 12
    Retrieving titles in the namespace 13
.    0 titles retrieved in the namespace 13
    Retrieving titles in the namespace 14
.    500 titles retrieved in the namespace 14
    Retrieving titles in the namespace 15
.    0 titles retrieved in the namespace 15
    Retrieving titles in the namespace 2600
.    12 titles retrieved in the namespace 2600
    Retrieving titles in the namespace 828
.    127 titles retrieved in the namespace 828
    Retrieving titles in the namespace 829
.    2 titles retrieved in the namespace 829
    Retrieving titles in the namespace 700
.    0 titles retrieved in the namespace 700
    Retrieving titles in the namespace 701
.    0 titles retrieved in the namespace 701
    Retrieving titles in the namespace 2300
.    0 titles retrieved in the namespace 2300
    Retrieving titles in the namespace 2301
.    0 titles retrieved in the namespace 2301
    Retrieving titles in the namespace 2302
.    0 titles retrieved in the namespace 2302
    Retrieving titles in the namespace 2303
.    0 titles retrieved in the namespace 2303
3458 page titles loaded
Titles saved at... enwikishianet-20180619-titles.txt
Retrieving the XML for every page from "start"
Server is slow... Waiting some seconds and retrying...
An error have occurred while retrieving "Main_Page"
Please, resume the dump, --resume

**Comment by nemobis** [comment]
"No such special page" http://en.wikishia.net/view/Special:Export

The sysadmin disabled export, not much we can do here. With issue #311 you can try and do without Special:Export, by invoking the option --xmlrevisions. Works for me.
