### ISSUE TITLE
URLEncoded Image Filenames

### ISSUE THREAD

**Issue by wertercatt** [WikiTeam/wikiteam#324]
Save the names of images as URLEncoded strings instead of the raw Unicode page names. This will prevent filesystem errors when trying to write them in Windows. For example, [this file on the Buddyfight wiki](http://buddyfight.wikia.com/wiki/File%3A%22Demonic%20Descent%20Sword%20of%20the%20King%22%20Laevateinn%20%28Anime-NC%29.png) will error out when dumpgenerator.py is run on Windows. However, if the filename was URLEncoded, it would be written properly.

**Comment by nemobis** [comment]
wertercatt, 28/08/2018 03:21:
> Save the names of images as URLEncoded strings instead of the raw 
> Unicode page names. This will prevent filesystem errors when trying to 
> write them in Windows.

I like URL-encoding filenames, but they create extra steps for GNU/Linux 
and UNIX-like users, which would then need to un-escape everything 
whenever they wanted to import the files into a new wiki (although one 
can argue they already need to do something about truncated long filenames).

However, we could catch an exception and print the file in URL-encoded 
form, with a warning that the file should not be uploaded on Internet 
Archive and a suggestion to use a proper operating system and file 
system for archival purposes.

**Comment by wertercatt** [comment]
...geez, my connection must have been dying

**Comment by nemobis** [comment]
Windows support is #73

**Comment by cooperdk** [comment]
> wertercatt, 28/08/2018 03:21:
> Save the names of images as URLEncoded strings instead of the raw Unicode page names. This will prevent filesystem errors when trying to write them in Windows.
> I like URL-encoding filenames, but they create extra steps for GNU/Linux and UNIX-like users, which would then need to un-escape everything whenever they wanted to import the files into a new wiki (although one can argue they already need to do something about truncated long filenames). However, we could catch an exception and print the file in URL-encoded form, with a warning that the file should not be uploaded on Internet Archive and a suggestion to use a proper operating system and file system for archival purposes.

... And what is a proper operating system? Do I need to direct you towards the statistics on which OS'es are most common? No? I didn't think so.

**Comment by TheTechRobo** [comment]
They're not saying Windows isn't popular. But Microsoft made some pretty awful design decisions for backwards compatibility. It makes programming for Windows extremely difficult. For example,  here _shouldn't_ be any reason that so many characters are disallowed, but there is.
