### ISSUE TITLE
uploader.py skips archives

### ISSUE THREAD

**Issue by Jannis234** [WikiTeam/wikiteam#326]
It seems like uploader.py doesn't find and upload everything. I've tried uploading a single wiki, but it only found *-history.xml.7z and skipped *-wikidump.7z.
Looks like this can be fixed by removing the "break" statement on line 69.

**Comment by d235j** [comment]
Yep, I just ran into this myself.

**Comment by nemobis** [comment]
You're right, it's currently uploading only the first it finds and that's incorrect. We don't need that `break` any more because we're no longer iterating through as many files as before.
