### ISSUE TITLE
Restore a mediawiki dump

### ISSUE THREAD

**Issue by jibanes** [WikiTeam/wikiteam#332]
I took a snapshot of a mediawiki site, which has now disappeared, and I would like to restore it somewhere else, do you have steps that describe this, all I have is this directory: "1429342184_mediawiki-20181217-wikidump", which is about 33MB.

**Comment by nemobis** [comment]
jerome ibanes, 17/12/18 16:02:
> I took a snapshot of a mediawiki site, which has now disappeared, and I 
> would like to restore it somewhere else, do you have steps that describe 
> this,

Congratulations for saving a wiki and (soon) bringing it back to life. 
This is strictly a MediaWiki question, but here's the manual:
https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps

**Comment by jibanes** [comment]
Amazing, thank you, I didn't know the export format was compatible; I just tried it worked great; many thanks to the wikiteam!

**Comment by nemobis** [comment]
Good. Do share the resuscitated wiki with us, it helps with our motivation. :)
