### ISSUE TITLE
How can I edit and view wikimedia xml.bz2 dumps at the same time?

### ISSUE THREAD

**Issue by repomorphic** [WikiTeam/wikiteam#333]
Hi, there. I am looking for a tool that can edit and view Wikimedia xml.bz2 dumps at the same time to create my local English Wiktionary copy. I have done some research about but only I can found Wikimedia read-only tools such as wikitaxi,bz2reader. Any advice appreciated. Thanks.

**Comment by nemobis** [comment]
repomorphic, 26/12/18 22:48:
> Hi, there. I am looking for a tool that can edit and view Wikimedia 
> xml.bz2 dumps at the same time to create my local English Wiktionary copy.

No such thing is possible. What you're looking for is called a parser. 
The easiest solution is to install your own MediaWiki instance and make 
your modifications there after the import.

I'm afraid this is not in scope for WikiTeam, but you can find 
interested people in Wiktionary-l:
https://lists.wikimedia.org/mailman/listinfo/wiktionary-l

Federico
