### ISSUE TITLE
Error on upload to archive.org

### ISSUE THREAD

**Issue by reit-c** [WikiTeam/wikiteam#335]
I have been having difficulty uploading an archive (generated via dumpgenerator.py) to archive.org. I followed the tutorial instructions, but I am getting the following error:

```
# python uploader.py mywikis
Please install the wikitools 1.3+ module if you want to use --xmlrevisions.
Please install the lxml module if you want to use --xmlrevisions.
0 dumps uploaded previously
#########################################################################
# Uploading https://animefeet.fandom.com/api.php
#########################################################################
animefeetfandomcom-20190216-wikidump.7z found
Traceback (most recent call last):
  File "uploader.py", line 285, in <module>
    main()
  File "uploader.py", line 282, in main
    upload(wikis, config, uploadeddumps)
  File "uploader.py", line 74, in upload
    item = get_item('wiki-' + wikiname)
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/api.py", line 116, in get_item
    return archive_session.get_item(identifier, request_kwargs=request_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/session.py", line 229, in get_item
    item_metadata = self.get_metadata(identifier, request_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/internetarchive/session.py", line 257, in get_metadata
    raise type(exc)(error_msg)
requests.exceptions.RequestException: Error retrieving metadata from https://archive.org/metadata/wiki-animefeetfandomcom, You are attempting to make an HTTPS request on an insecure platform, please see:

	https://internetarchive.readthedocs.org/en/latest/troubleshooting.html#https-issues
```

**Comment by nemobis** [comment]
Thank you for your dump.

reit-c, 23/02/19 02:46:
> |requests.exceptions.RequestException: Error retrieving metadata from 
> https://archive.org/metadata/wiki-animefeetfandomcom, You are attempting 
> to make an HTTPS request on an insecure platform, please see: 
> https://internetarchive.readthedocs.org/en/latest/troubleshooting.html#https-issues|

Well, have you followed this suggestion? The new location is
<https://archive.org/services/docs/api/internetarchive/troubleshooting.html#https-issues>

Usually HTTPS errors are due to outdated operating system/root 
certificates or outdated Python.

**Comment by reit-c** [comment]
No I hadn't, as the troubleshooting page appeared to have disappeared. I have it working now, the issue was having an older version of Python. I download 2.7.9's source, compiled it, installed pip to it, installed the requirements, then reran the upload and it appears to be working.

**Comment by nemobis** [comment]
Ok, glad you fixed it and thanks for the update.
