### ISSUE TITLE
dumpgenerator.py should validate the completeness of the dump before exit

### ISSUE THREAD

**Issue by Wikiteam-on-Windows** [WikiTeam/wikiteam#339]
#214 details an idea for making launcher.py automatically validate downloads, dumpgenerator.py should probably also

Both wikiteam's main github page and the Tutorial do not currently have any information on using launcher.py and recommend to use dumpgenerator.py, if anyone can improve those pages it would be useful (I recently added a workaround guide to the Tutorial to get Wikiteam "working" on Windows by just running it on VirtualBox instead)

https://github.com/WikiTeam/wikiteam/wiki/Tutorial#Checking_dump_integrity currently has a section recommending people to do <code>grep "<title>" *.xml -c;grep "<page>" *.xml -c;grep "</page>" *.xml -c;grep "<revision>" *.xml -c;grep "</revision>" *.xml -c </code> then look at the numbers returned and know there's corruption if any of the first three numbers are different (number of titles matching with the start of page tags and the end of page tags) or if the last two numbers are not both the same as each other also (start of revision tags and end of revision tags)

Doing it by hand that way works, but it's the kind of extra step people might skip over due to not reading properly, or in a hurry, or worse get it wrong but write it was validated because they're tired and misread a number or whatever :) putting history in the hands of one little mistake someone can make

It's also possible to FIX the corruption of the XML by hand, if when downloading you check the dumpgenerator.py log when it gets interrupted and take a careful screenshot/note of where it got left off, then after resuming and later when it's all finished, what seems to be normal is that the page will be missing the end </page> tag and will have been downloaded again twice as one as a sort of FrankenPage - you can end the tag properly and delete the second copy of the page (on the original wiki you can visit the Special:Export page by hand and look up these 3 pages and compare that everything is how it should be, though hashes not being transferred for "File:" pages seems normal). 
-- But automating that would probably be best, as opening dozens of gigabytes big text files and manipulating by hand is introducing another big risk to human error in the archives that might not get noticed until years later :)

Corruption could also be less likely to happen if the way that Wikiteam deals with a resume from connection interruption was better: #340 

Corruption could also be less likely to happen if there was more than a 10 second timeout: #338 

( Someone DID write on the tutorial "<code>re-download, a bit boring, and it can fail again...), or if you don't care to lose the corrupt pages, exclude them with this script (TO DO).</code>" I cannot find who wrote that sentence on https://github.com/WikiTeam/wikiteam/wiki/Tutorial/_history as the oldest revision available on 2014-06-30 from @Hydriz edit summary is "<code>Rename to tutorial</code>" without a reference to who the authors of the page originally were or a link to the old page :( It seems someone was planning to fix it those 5 years ago but maybe forgot about it and left it in the Tutorial)

**Comment by nemobis** [comment]
Thank you for testing dumpgenerator.

I don't think we're going to do this, because it's not possible to fully automate the validation and the only point in doing it within dumpgenerator itself would be to automate the redownload. We don't want to encourage users to do that mindlessly, because it's better to use launcher.py and just start a dump from scratch unless you really know what you're doing. Also, if someone calls dumpgenerator functions from outside we'd like to reduce the risk of infinite loops rather than increase them.

If you have problems with one specific wiki which don't happen with others, please file an issue about that wiki. We may able to help and it's always fun to archive one more wiki, while it's not fun at all to deal with generic issues. Thank you.
