### ISSUE TITLE
uploader.py: "Connection aborted" on uploading to an existing item by another user

### ISSUE THREAD

**Issue by Czechball** [WikiTeam/wikiteam#344]
Python version: `Python 2.7.16`
OS: `Debian GNU/Linux 10 (buster) on Windows 10 x86_64` (Windows Subsystem Linux)
Kernel version: `4.4.0-18362-Microsoft`

Command used:  `python2.7 uploader.py thinkwikiorg_w.txt`

Command output:
```
0 dumps uploaded previously
#########################################################################
# Uploading http://www.thinkwiki.org/w/api.php
#########################################################################
thinkwikiorg_w-20200121-wikidump.7z found
thinkwikiorg_w-20200121-wikidump.7z was not uploaded before
http://www.thinkwiki.org/w/api.php thinkwikiorg_w 20200121 thinkwikiorg_w-20200121-wikidump.7z
Item already exists.
http://www.thinkwiki.org/w/api.php thinkwikiorg_w-20200121-wikidump.7z Error when uploading?0:02:50
('Connection aborted.', error(32, 'Broken pipe'))
 uploading thinkwikiorg_w-20200121-wikidump.7z: [################################] 9/107 - 00:00:31
```

File: [thinkwikiorg_w.txt](https://github.com/WikiTeam/wikiteam/files/4090609/thinkwikiorg_w.txt) (just contains `http://www.thinkwiki.org/w/api.php`)
The Wiki was previously dumped using the command `python2.7 dumpgenerator.py http://www.thinkwiki.org/wiki/ --xml --images`, which was successful without any errors.

The folder containing the dump was then compressed using 7zip GUI using the following settings: (sorry if some options aren't the exact ones in the actual gui, I have 7zip in Czech language so I had to translate them)
```
Format: 7z
Compression level: Ultra
Comprimation method: LZMA2
Dictionary size: 64MB
Word size: 64
Block size: 4 GB
```

The resulting archive name was `thinkwikiorg_w-20200121-wikidump.7z`

Please note that I have already succesfully uploaded other wikis before using the same command syntax and 7z settings.

**Comment by nemobis** [comment]
Thank you for using WikiTeam and for archiving thinkwiki.

David Jenne, 21/01/20 13:38:
> |http://www.thinkwiki.org/w/api.php thinkwikiorg_w-20200121-wikidump.7z 
> Error when uploading?0:02:50 ('Connection aborted.', error(32, 'Broken 
> pipe')) uploading thinkwikiorg_w-20200121-wikidump.7z: 
> [################################] 9/107 - 00:00:31|

This is just a temporary connection error, have you tried launching 
uploader.py again?

**Comment by Czechball** [comment]
Hello, thanks for your swift reply and sorry for not responding earlier myself.

Unfortunately, this doesn't seem to be the case. The issue persists after multiple attempts and even on different networks. I have verified the stability and speed of internet on said networks, but the script fails regardless.

Here is the output of my last three attempts:
```
czechball@latitude-david:~/wikiteam$ python2.7 uploader.py thinkwikiorg_w.txt
0 dumps uploaded previously
#########################################################################
# Uploading http://www.thinkwiki.org/w/api.php
#########################################################################
thinkwikiorg_w-20200121-wikidump.7z found
thinkwikiorg_w-20200121-wikidump.7z was not uploaded before
http://www.thinkwiki.org/w/api.php thinkwikiorg_w 20200121 thinkwikiorg_w-20200121-wikidump.7z
Item already exists.
http://www.thinkwiki.org/w/api.php thinkwikiorg_w-20200121-wikidump.7z Error when uploading?00:02:01
('Connection aborted.', error(32, 'Broken pipe'))
 uploading thinkwikiorg_w-20200121-wikidump.7z: [################################] 17/107 - 00:00:25
czechball@latitude-david:~/wikiteam$ python2.7 uploader.py thinkwikiorg_w.txt
0 dumps uploaded previously
#########################################################################
# Uploading http://www.thinkwiki.org/w/api.php
#########################################################################
thinkwikiorg_w-20200121-wikidump.7z found
thinkwikiorg_w-20200121-wikidump.7z was not uploaded before
http://www.thinkwiki.org/w/api.php thinkwikiorg_w 20200121 thinkwikiorg_w-20200121-wikidump.7z
Item already exists.
http://www.thinkwiki.org/w/api.php thinkwikiorg_w-20200121-wikidump.7z Error when uploading?00:01:38
('Connection aborted.', error(32, 'Broken pipe'))
 uploading thinkwikiorg_w-20200121-wikidump.7z: [################################] 26/107 - 00:00:32
czechball@latitude-david:~/wikiteam$ python2.7 uploader.py thinkwikiorg_w.txt
0 dumps uploaded previously
#########################################################################
# Uploading http://www.thinkwiki.org/w/api.php
#########################################################################
thinkwikiorg_w-20200121-wikidump.7z found
thinkwikiorg_w-20200121-wikidump.7z was not uploaded before
http://www.thinkwiki.org/w/api.php thinkwikiorg_w 20200121 thinkwikiorg_w-20200121-wikidump.7z
Item already exists.
http://www.thinkwiki.org/w/api.php thinkwikiorg_w-20200121-wikidump.7z Error when uploading?00:01:29
('Connection aborted.', error(32, 'Broken pipe'))
 uploading thinkwikiorg_w-20200121-wikidump.7z: [################################] 22/107 - 00:00:31
```

**Comment by nemobis** [comment]
No worries for speed of reply!

David Jenne, 22/01/20 03:18:
> Unfortunately, this doesn't seem to be the case. The issue persists 
> after multiple attempts and even on different networks. I have verified 
> the stability and speed of internet on said networks, but the script 
> fails regardless.

There are all sorts of reason you can get your connection to the 
Internet Archive closed during upload. Have you successfully uploaded 
other files of this size over the command line? Hm, the biggest I see is 
over 1 GB in <https://archive.org/details/wiki-wikisps_picz>.

Just to be sure, do you have permissions to upload to 
https://archive.org/details/wiki-thinkwikiorg_w ? That's an item I 
created, so only I and the admins of the wikiteam collections (and 
higher) can upload to it. I think IA used to refuse your upload 
immediately but I've not checked recently.

I would suggest that you try and upload the file from the web interface 
to see what happens. It might also be a misguided antivirus or something.

Federico

**Comment by Czechball** [comment]
I'm not sure how to upload to the item you sent, but I'm guessing that I'm supposed to see the editing buttons as I see on my own uploads. Since I don't see these buttons on the link you sent, I think that I don't have a permission to upload to this item.

**Comment by nemobis** [comment]
David Jenne, 27/01/20 11:06:
> Since I don't see these buttons on the link you sent, I think that I 
> don't have a permission to upload to this item.

Indeed. So this is not a bug, but in general if you have dumps to upload 
to other users' items (preferably multiple at once, easy to download 
with wget) just drop a line on #wikiteam in EFNet and someone will do it 
for you.
