### ISSUE TITLE
UnicodeEncodeError interrupting downloads

### ISSUE THREAD

**Issue by mc-123** [WikiTeam/wikiteam#374]
Apologies for my limited knowledge as I am new to Python 3 (and have little experience with Python 2 syntax). 

The following error is thrown up by inability to encode ASCII for a title referred to in an error message:

Traceback (most recent call last):
  File "dumpgenerator.py", line 2493, in <module>
    main()
  File "dumpgenerator.py", line 2483, in main
    resumePreviousDump(config=config, other=other)
  File "dumpgenerator.py", line 2200, in resumePreviousDump
    session=other['session'])
  File "dumpgenerator.py", line 1460, in generateImageDump
    text=u'The page "%s" was missing in the wiki (probably deleted)' % (title.decode('utf-8'))
  File "/home/mjc/Applications/anaconda2/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 12: ordinal not in range(128)

Would it be possible to add errors="ignore" to the title.decode method to avoid strict handling of errors breaking downloads?

**Comment by nemobis** [comment]
mc-123, 18/02/20 11:44:
> Would it be possible to add errors="ignore" to the title.decode method 
> to avoid strict handling of errors breaking downloads?

Maybe, but that's not what we need. The real solution is to clearly 
handle Unicode at the boundary between the program and its input/output, 
so that only Unicode is carried around within the program.

There is already a report (or possibly more) on this error upon resuming.

**Comment by nemobis** [comment]
Same as https://github.com/WikiTeam/wikiteam/issues/136#issuecomment-524633859 , let's continue there.
