### ISSUE TITLE
Refuses to work when printed sentences are not in parentheses

### ISSUE THREAD

**Issue by pantsmode** [WikiTeam/wikiteam#375]
When I launched the dumpgenerator in my command prompt (I have the latest version of Python as far as I am concerned), it comes back telling me that the print commands are not written right and that they should be in parentheses.

**Comment by pantsmode** [comment]
Update: found out this can be used in Python 2.7, but that is also when you should know how to run _anything_ in Python, implying your Windows machine won't break apart the moment you try to run a script outside the Python folder in the command prompt.

**Comment by nemobis** [comment]
We currently don't support Python 3, sorry. The main discussion on the matter is at https://github.com/WikiTeam/wikiteam/pull/331
