### ISSUE TITLE
0 edits [downloaded]

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#38]
_From [nemow...@gmail.com](https://code.google.com/u/101255742639286016490/) on September 02, 2011 10:02:06_

Sometimes, a downloaded pages is reported to have 0 edits. The history of a page can't be empty, so it doesn't mean anything: either the log should be corrected, or something needs to be done when this happens. If no revisions are actually downloaded, it could be just a temporary server problem (in my current downloading this happens occasionally with a single title or a cluster of them) and the script should retry. Some examples ( http://wikicafe.metacafe.com ):

Downloaded 345440 pages
    4074553, 0 edits
    4074554, 0 edits
    4074555, 0 edits
    4074556, 2 edits
    4074557, 2 edits
    4074559, 0 edits
    4074560, 0 edits
    4074561, 2 edits
    4074562, 0 edits
    4074563, 0 edits

Downloaded 351610 pages
    4083509, 1 edits
    4083510, 1 edits
    4083511, 1 edits
    4083515, 2 edits
    4083516, 2 edits
    4083519, 2 edits
    408352, 2 edits
    4083521, 2 edits
    4083522, 0 edits
    4083524, 2 edits

$ grep "<title>" *.xml -c;grep "<page>" *.xml -c;grep "</page>" *.xml -c;grep "<revision>" *.xml -c;grep "</revision>" *.xml -c
1751675
1751711
1751745
3114970
3115016

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=38_

**Comment by nemobis** [comment]
Wiki Wikicafe Metacafe, I had almost forgotten this old friend of mine. Looks like it's long dead, with all its glorious weirdness. I had a half-completed XML for years on my hard disk but it seems that the heroic dump of 2011 will remain the only one in history (with the legendary User_talkMarkjp.7z, the spammy talkpage which 7z compressed by a factor of over 6000, from 53 GiB to 8 MiB):
https://archive.org/details/wiki-wikicafe.metacafe.com_en
