### ISSUE TITLE
Make the dumper be able to dump files with disallowed characters in Windows

### ISSUE THREAD

**Issue by forkiesassds** [WikiTeam/wikiteam#380]
On Windows if you try to dump an wiki which has files that contain disallowed characters in the file name such as ?, :, *, etc, it errors out and you are forced to skip the file with these characters.

**Comment by robkam** [comment]
For example with `python dumpgenerator.py --api=https://electronicmusic.fandom.com/api.php --images` it chokes on the file name [Roland_Aira_TR-8_VS_TR-909_Unbiased_Comparison._HQ*****](https://electronicmusic.fandom.com/wiki/File:Roland_Aira_TR-8_VS_TR-909_Unbiased_Comparison._HQ*****) 

> Traceback (most recent call last):
>   File "dumpgenerator.py", line 2528, in <module> main()
>   File "dumpgenerator.py", line 2520, in main createNewDump(config=config, other=other)
>   File "dumpgenerator.py", line 2099, in createNewDump session=other['session'])
>   File "dumpgenerator.py", line 1473, in generateImageDump imagefile = open(filename3, 'wb')
> IOError: [Errno 22] invalid mode ('wb') or filename: u'./electronicmusicfandomcom-20200617-wikidump/images/Roland Aira TR-8 VS TR-909 Unbiased Comparison. HQ*****'

**Comment by nemobis** [comment]
This is also covered at https://github.com/WikiTeam/wikiteam/issues/324 and https://github.com/WikiTeam/wikiteam/issues/73 . We don't invest in specific support for Windows, but we'll try to consider patches which go in that direction and don't disturb non-Windows users.
