### ISSUE TITLE
dumpgenerator.py doesn't work with Miraheze wiki farm wikis

### ISSUE THREAD

**Issue by robkam** [WikiTeam/wikiteam#382]
Trying to dump xml and images using dumpgenerator.py at https://sdiy.info/w/api.php produces
```
Checking api.php... http://www.sdiy.info/w/api.php
api.php is OK
Checking index.php... http://www.sdiy.info/w/index.php
Error in index.php, please, provide a correct path to index.php
```
in the browser index.php just redirects to https://sdiy.info/wiki/Main_Page

See also the thread [Wiki sysops can't use WikiTeam script to backup their wikis.](https://phabricator.miraheze.org/T2418) at Miraheze.

**Comment by nemobis** [comment]
Works for me, please share your exact command line.

**Comment by robkam** [comment]
C:\Python27\python.exe dumpgenerator.py --api=http://www.sdiy.info/w/api.php --xml --images

**Comment by nemobis** [comment]
That works in master, but might have failed in previous versions because you're passing the HTTP URL instead of HTTPS. POST to HTTP fails.

**Comment by robkam** [comment]
I get the same with https
C:\Python27\python.exe dumpgenerator.py --api=https://www.sdiy.info/w/api.php --xml --images
```
Checking api.php... https://www.sdiy.info/w/api.php
api.php is OK
Checking index.php... https://www.sdiy.info/w/index.php
Error in index.php, please, provide a correct path to index.php
```

**Comment by robkam** [comment]
Okay never mind, it works if I remove the www from the URL. Thanks.

**Comment by robkam** [comment]
Still not working, that fetched the images and started with the xml but truncated it after 348 kb

Also I can't get another to work, it's abetter example as it's on the Miraheze domain
C:\Python27\python.exe dumpgenerator.py --api=https://scruffy.miraheze.org/w/api.php --xml --images 
```
Checking api.php... https://scruffy.miraheze.org/w/api.php
api.php is OK
Checking index.php... https://scruffy.miraheze.org/w/index.php
Error in index.php, please, provide a correct path to index.php
```

**Comment by robkam** [comment]
I've been using an old version of dumpgenerator.py
