### ISSUE TITLE
Empty desc files.

### ISSUE THREAD

**Issue by robkam** [WikiTeam/wikiteam#383]
With C:\Python27\python.exe dumpgenerator.py --xml --images  --api=https://sdiy.miraheze.org/w/api.php
The desc files are all 0 kb
e.g. for these files where there is text (or a template) in the summary.
https://sdiy.info/wiki/File:Cgs_photo_cgs108v10_vca.jpg
https://sdiy.info/wiki/File:Prophet_5_analog_section_block_diagram.png

**Comment by nemobis** [comment]
Rob Kam, 09/06/20 10:25:
> The desc files are all 0 kb

There's already a bug report for this. It's about guessing whether 
exportnowrap can be used or not; the current options work in most cases. 
Patches welcome.

**Comment by robkam** [comment]
Duplicate of #55
