### ISSUE TITLE
Unicode error

### ISSUE THREAD

**Issue by derenrich** [WikiTeam/wikiteam#391]
So when dumping a wiki I'm getting an incomplete dump (after a restart). I believe this is caused by this error
```
dumpgenerator.py:1103: UnicodeWarning: Unicode unequal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif seeking and title != start:
```
It erroneously thinks it has fetched all pages and then gives up. 

Should probably just rewrite in py3 to avoid things like this

**Comment by nemobis** [comment]
Daniel Erenrich, 14/07/20 20:37:
> Should probably just rewrite in py3

There's already a task for that and a branch in my fork. If you want you
can contribute to that branch, or contribute tests to reproduce the
issue reliably.

**Comment by nemobis** [comment]
The first part is at #199
