### ISSUE TITLE
is there some resource to mapping the same entity/word/concept between different language?

### ISSUE THREAD

**Issue by loveJasmine** [WikiTeam/wikiteam#404]
for example, Washington (eng) and 华盛顿 (chn) are the same concept/entity, but in different language?

Is there some resource to tell me the tokens about Washington in other language?

Does WiKipedia provide this?

**Comment by nemobis** [comment]
yk_data, 20/01/21 10:37:
> for example, Washington (eng) and 华盛顿 (chn) are the same concept/entity, but in different language?

I think you're looking for Wikidata or Unicode CLDR.

Note that this issue tracker is not a support forum for all the millions 
of wikis in the world. You can ask such questions on StackExchange or 
another forum, if you can't find a specific community's support channels.
