### ISSUE TITLE
WikiApiary bots are dead - can we get permission to resurrect them from their graves?

### ISSUE THREAD

**Issue by Coloradohusky** [WikiTeam/wikiteam#406]
Our WikiApiary bots ([WikiTeam](https://wikiapiary.com/wiki/Special:Contributions/WikiTeam) and [Emijrpbot](https://wikiapiary.com/wiki/Special:Contributions/Emijrpbot)) haven't been active since early 2016 - how would I (or anyone) go about reviving them?

**Comment by nemobis** [comment]
Thanks for asking. If you want to help, as a first step I suggest to 
check the code of those bots, update it if necessary, and run it under a 
new username registered by you. The bot policy is not so strict at 
WikiApiary, I believe, so you can make a few hundred edits if you go 
slow, but maybe don't make thousands before making sure it's fine.

Some of the scripts might be in https://github.com/emijrp/emijrp

**Comment by Coloradohusky** [comment]
https://wikiapiary.com/wiki/User:ColoradohuskyBOT is operational (has been for two weeks or so, just forgot to update issue). Thanks!

**Comment by nemobis** [comment]
Il 19/06/21 09:09, Coloradohusky ha scritto:
> https://wikiapiary.com/wiki/User:ColoradohuskyBOT  is operational

Thank you! And thank you for your uploads, I'll send a couple comments 
about these separately.
