### ISSUE TITLE
wikiadownlader.py: "No such file or directory: 'wikia.com'"

### ISSUE THREAD

**Issue by Shoibe** [WikiTeam/wikiteam#412]
`Traceback (most recent call last):
  File "wikiadownloader.py", line 41, in <module>
    f = open('wikia.com', 'r')
IOError: [Errno 2] No such file or directory: 'wikia.com'
`

**Comment by nemobis** [comment]
You need to run the script in the same directory where you have the list 
of the wiki names/domain names, which in this repository by default is 
called wikia.com.

**Comment by Shoibe** [comment]
is there any way to archive a fandom? (wikia changed names)

**Comment by Shoibe** [comment]
Traceback (most recent call last):
  File "wikiadownloader.py", line 82, in <module>
    fail_file.close()
NameError: name 'fail_file' is not defined
because of this

**Comment by nemobis** [comment]
Use dumpgenerator or launcher.py with the real URL and (preferably) 
--xmlrevisions
