### ISSUE TITLE
Requirements installation issue

### ISSUE THREAD

**Issue by EstebanOD** [WikiTeam/wikiteam#413]
I did `pip install --upgrade -r requirements.txt`
It installed everything

Then I try to run `python dumpgenerator.py --images --xml --curonly naruto.fandom.com`
But it tells me `  File "C:\Users\Esteb\Documents\wikiteam-master\dumpgenerator.py", line 25
    print "Please install the kitchen module."
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("Please install the kitchen module.")?`

Even tho the kitchen module is already installed!
To make sure, I did `pip install kitchen` once again, but it doesn't solve the problem...
I'm not a pro at python, so maybe I'm doing something incorrectly, however, I followed every instruction I was given.

**Comment by nemobis** [comment]
Il 14/09/21 21:04, EstebanOD ha scritto:
> I'm not a pro at python, so maybe I'm doing something incorrectly, however I followed every instructions I was given.

You're using python3, which is not supported.

**Comment by EstebanOD** [comment]
oh lame

**Comment by nemobis** [comment]
Il 14/09/21 21:36, EstebanOD ha scritto:
> oh lame

I agree! You can help by testing 
https://github.com/WikiTeam/wikiteam/pull/409 . Unfortunately we don't 
really support Windows either, as none of the devs use it: if it works, 
it's just luck.
