### ISSUE TITLE
Setting more than 5 reconnecting requests.

### ISSUE THREAD

**Issue by Phenyan** [WikiTeam/wikiteam#416]
Is there any way to make it try to reconnect indefinitely, as opposed than just 5 times than default?
>   In attempt 1, XML for "Pagename" is wrong. Waiting 20 seconds and reloading…
>  In attempt 2, XML for "Pagename" is wrong. Waiting 40 seconds and reloading…
>  In attempt 3, XML for "Pagename" is wrong. Waiting 60 seconds and reloading…
>  In attempt 4, XML for "Pagename" is wrong. Waiting 80 seconds and reloading…

I’m downloading ‘https://monstergirlencyclopedia.fandom.com/’ , which takes for circa 3 days.
It downloads those Wikis by three periods. With the Articles, Talk pages and the Images.
Precisely, there always is some issue, when on ‘Board Thread:Roleplay/@comment’, which takes for quite long (I was never able to go past that period, in spite of attemping to download it 8 times already), so far it either was unable to connect to the server, or my internet wouldn’t connect any more.
When the former does happens, it shows:
> HTTP Error 503.
> Server error, max retries exdeeded.

When the latter happens, it instead shows:
> We have retried 5 times
> MediaWiki error for "Board_Thread:Roleplay/@comment-2437678-2016011720544/@comment-24376783-20160119205409", network error or whatever...
> Saving in the error log, and skipping...

And it shows no:
> Do you want to resume ([yes, y), [no, n]?

Option when I try to renew the dump (as wass when I’ve encountered different errors trying to download different Wikis previously), neither does adding adding ‘--resume --path=/previousdumpdirectory’ (in this case the directory was called ‘monstergirlencyclopediafandomcom-20211207-wikidump’) seems to work, it just says that:
> There is no config file, we can't resume. Start a new dump.

(Mind you the number of those folders is already 8, some over 2 GBs.)
Using 'python dumpgenerator.py --api=https://monstergirlencyclopedia.fandom.com/api.php --xml --images' will just make it start downloading those Talk pages from the very beginning, starting with ‘Talk::1: Eyes of th Goshaw/@comment’
Please tell me if there’s a way to make it try reconnecting indefinitely, Fandom (formerly Wikia) will be closing down all of NSFW-focused Wikis at 13.12.2021 and at this point I just see it as simply impossible to ever download it.

**Comment by nemobis** [comment]
Il 09/12/21 15:16, Phenyan ha scritto:
> I’m downloading ‘https://monstergirlencyclopedia.fandom.com/’  , which takes for circa 3 days.

This wiki has 1M pages with 1.2M edits, if the statistics are to be 
trusted. Please use --xmlrevisions to reduce the number of requests 
you'll need by ~50 times.

It sounds like we need a mass archival of those Wikia wikis. It would be 
very useful to contribute a list of their domain names.

**Comment by Phenyan** [comment]
@nemobis Surely I can do that! Fandom (formerly Wikia) said to be deleting NSFW-focused Wikis, but they posponed that date to 13.12.2021 due to Christmas season. In specific however only the owners of MG (Monster Girl/Mon-musu) Wikis received such monits from Sannse, which promted them to do that. Even if their language was non-English, they were’t translated.
In the end they said to postpone this due to not contacting all owners on time.
Those specific Wikis were hit:
MGQ:
https://monstergirlquest.fandom.com/wiki/MonsterGirlQuest_Wiki (took me around a day to download with all revisions, encountered two stroke errors whilst doing so, and thus had to move two files. A few non-Latin filenames were shortened automatically).
MGE:
https://monstergirlencyclopedia.fandom.com/wiki/Monster_Girl_Encyclopedia (takes circa 3 days to download whole with all of revisions, but was unable to do so, just today their servers refused to reconnect after 5 automatic attempts).
https://monstergirlencyclopedia.fandom.com/pt-br/wiki/Monster_Girl_Encyclopedia_Wiki (a Brazilian version).
Both of those MGE Wikis were put on archive.org, but I felt it was an incomplete download, so I wanted to do it myself.
At one point a Russian language version also existed, but I was unable to find it again.
MGI (Monster Girl Island):
https://mgi.fandom.com/wiki/Monster_Girl_Island_Wiki (this is the main one which received a monit).
https://monster-girl-island.fandom.com/wiki/Monster_Girl_Island_Wikia (this one is abandoned and received none, I still archived it).
Additionaly Monster Girl Dreams owners also moved it to Miraheze.org, as did the owners of all previous ones:
https://monstergirldreams.fandom.com/wiki/Monster_Girl_Dreams_Wiki
To my knowledge however they received no information of its planned enclosure.
There’s also a Monster Musume: Everyday Life with Monster Girls one:
https://dailylifewithamonstergirl.fandom.com/wiki/Daily_Monster_Girls_Wiki (took me circa 2 days to download with all of its revisions, a few too long mostly non-Latinate filenames were automatically shortented as well).
https://monster-musume-no-iru-nichijou.fandom.com/es/wiki/Wiki_Monster_musume_no_iru_nichijou
Particularly the Spanish language version one received a monit instead, but after contacting Sannse she said that they won’t be closed, as the title is ecchi.
I also archived this one:
https://12-beast.fandom.com/wiki/12_Beast_Wiki
Which is another Mr. Okayado title linked to Monster Musume. They received no monit at all.
If this is an incorrect place to submit this info I’ll do it elsewhere.

**Comment by nemobis** [comment]
Il 10/12/21 17:46, Phenyan ha scritto:
> If this is an incorrect place to submit this info I’ll do it elsewhere.

It's ok like this, but if you want you can add them to 
https://wikiapiary.com/wiki/Main_Page and submit an URL list (one 
api.php URL per line) in 
https://github.com/WikiTeam/wikiteam/tree/master/listsofwikis/mediawiki

Federico
