### ISSUE TITLE
WikiApiary doesn't mark every defunct wiki as defunct

### ISSUE THREAD

**Issue by rowanjacobs** [WikiTeam/wikiteam#422]
I've noticed a lot of the sites on WikiApiary that are marked as non-defunct appear to be defunct (DNS doesn't resolve, or the link goes to a 404 page, or a completely different page). How do sites get marked as defunct? Is it an automatic process? Or should I be editing these pages when I come across them?

**Comment by nemobis** [comment]
Il 05/02/22 18:37, Rowan Jacobs ha scritto:
> Or should I be editing these pages when I come across them?

Yes.

Wikiapiary is a separate project from Wikiteam. Its bots have their own 
repository:
https://github.com/WikiApiary/wikibees
