### ISSUE TITLE
kitchen module

### ISSUE THREAD

**Issue by Skhsouravhalder** [WikiTeam/wikiteam#426]
File "/data/data/com.termux/files/home/wikiteam/dumpgenerator.py", line 25
    print "Please install the kitchen module."
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

How to solve it

**Comment by nemobis** [comment]
Il 25/03/22 20:52, Sourav halder ha scritto:
> SyntaxError: Missing parentheses in call to 'print'. Did you mean print(...)?

This means you've tried to run python3, which is not supported yet. See 
https://github.com/WikiTeam/wikiteam/issues/395
