### ISSUE TITLE
kitchen module

### ISSUE THREAD

**Issue by Skhsouravhalder** [WikiTeam/wikiteam#427]
Please install the kitchen module.
Please install or update the Requests module.

How to solve it. Then I'm use 
import kitchen

And view

import: unable to open X server `' @ error/import.c/ImportImageCommand/348.

**Comment by nemobis** [comment]
Il 26/03/22 04:56, Sourav halder ha scritto:
> How to solve it.

You need to use python2.

**Comment by nemobis** [comment]
Duplicate of https://github.com/WikiTeam/wikiteam/issues/395
