### ISSUE TITLE
How to install pip onto 2.7?

### ISSUE THREAD

**Issue by mushgoo** [WikiTeam/wikiteam#461]
Not sure where else to put this because I dont know what programs still use python 2.7, mine says pip isn't installed and when I try to install pip it says not compatible. After fiddling around it gave me a link to a compatible version of pip, which when I try to install says this error message:

DEPRECATION: Python 2.7 reached the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 is no longer maintained. pip 21.0 will drop support for Python 2.7 in January 2021. More details about Python 2 support in pip can be found at https://pip.pypa.io/en/latest/development/release-process/#python-2-support pip 21.0 will remove support for this functionality.
c:\users\user\appdata\local\temp\tmpwiuo9s\pip.zip\pip\_vendor\urllib3\util\ssl_.py:424: SNIMissingWarning: An HTTPS request has been made, but the SNI (Server Name Indication) extension to TLS is not available on this platform. This may cause the server to present an incorrect TLS certificate, which can cause validation failures. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
c:\users\user\appdata\local\temp\tmpwiuo9s\pip.zip\pip\_vendor\urllib3\util\ssl_.py:164: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. You can upgrade to a newer version of Python to solve this. For more information, see https://urllib3.readthedocs.io/en/latest/advanced-usage.html#ssl-warnings
WARNING: Certificate did not match expected hostname: pypi.org. Certificate: {'notAfter': 'May 30 18:53:39 2024 GMT', 'subjectAltName': (('DNS', 'www.python.org'), ('DNS', '*.python.org'), ('DNS', 'docs.python.org'), ('DNS', 'downloads.python.org'), ('DNS', 'pypi.python.org')), 'subject': ((('commonName', u'www.python.org'),),)}
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'SSLError(CertificateError("hostname 'pypi.org' doesn't match either of 'www.python.org', '*.python.org', 'docs.python.org', 'downloads.python.org', 'pypi.python.org'",),)': /simple/pip/

Which as someone who doesn't do this stuff I have no idea what it means and how to fix it. Needing to download images from a fandom wikia haha. Thanks for any help

Update: I typed this to download another older version of pip
curl https://raw.githubusercontent.com/pypa/get-pip/master/2.7/get-pip.py --output C:\Users\user\Downloads\get-pip.py and it downloaded it, but says it's corrupted. :(

**Comment by ILC-YTP** [comment]
Try installing a new version of python 2.7, such as [this one](https://www.python.org/downloads/release/python-2718/l)
Had a similar issue on windows when installing the version directly linked in the github. Installed the latest version of 2.7 and ran it though powershell instead of CMD. It seems to work now for me.

**Comment by nemobis** [comment]
There are many articles around on how to install pip in python2 these days. For example, for Debian: https://www.linuxcapable.com/how-to-install-python-pip-pip3-on-debian-11-bullseye/

As for Windows issues, my recommendation to solve them is to avoid it and use GNU/Linux. Dual boot or even a live image saving to an external memory can do the trick, if you don't want to play with virtual images or ditch Windows entirely.

I'm closing this issue, but if someone else wants to help they still can (as ILC-YTP did).
