### ISSUE TITLE
Images have wrong filenames?

### ISSUE THREAD

**Issue by pbz134** [WikiTeam/wikiteam#478]
Hello,

I downloaded all images from https://metalgear.fandom.com/de/wiki/ using
`dumpgenerator.exe --images https://metalgear.fandom.com/de/wiki/`

However, the naming seem to be wrong.
What I did is, I extracted the links from the resulting "metalgearfandomcom_de-20240228-images.txt" file and this is what the downloads looks like:
![grafik](https://github.com/WikiTeam/wikiteam/assets/53271427/57d15f7f-b7db-48da-b9b4-9ae173bf59ea)

Unfortunately, I can't figure out a way how to directly download images with the dumpgenerator, which would probably fix the naming issue.

**Comment by nemobis** [comment]
Il 28/02/24 18:24, pbz134 ha scritto:
> However, the naming seem to be wrong.

Yes the filenames are unfortunately nonsense on Wikia wikis since they 
moved to a different CDN/whatever. On most wikis there's a close 
correspondence between filename on the wiki, filename on the filesystem 
and path in the URL. Not on Wikia.

**Comment by pbz134** [comment]
Okay, thank you for explaining!
