### ISSUE TITLE
Is there a way to create a MediaWiki XML dump from HTML pages on web.archive.org?

### ISSUE THREAD

**Issue by trenkert** [WikiTeam/wikiteam#482]
There are wikis preserved on archive.org which are now longer accessible on their original servers. Is there any way to download those wikis (mainly mediawiki installations) in full to import them into a fresh mediawiki installation and run them again locally?

**Comment by nemobis** [comment]
Il 29/06/24 21:03, Thomas Renkert ha scritto:
> There are wikis preserved on archive.org which are now longer accessible
>   on their original servers. 

Yes, thousands of them.

> Is there any way to download those wikis
> (mainly mediawiki installations) in full to import them into a fresh
> mediawiki installation and run them again locally?

Yes, just click the relevant download button on the sidebar or click 
"show all" and then copy the download URL for use with your preferred 
download manager (like wget).

Then see
https://www.mediawiki.org/wiki/Manual:Importing_XML_dumps

**Comment by trenkert** [comment]
thank you, I did not mean archive.org as in archived wiki xmls dumps, but the waybackmachine with the captured pages of a wiki. The xml dump does not exist on archive.org, but the waybackmachine has the pages captured. Is it possible to reconstruct an xml dump from pages captured on wayback?

**Comment by nemobis** [comment]
Not really. You'll need an HTML crawler customised for MediaWiki purposes and then a script to convert the HTML back to wikitext. There are some such partial solutions in https://www.mediawiki.org/wiki/Category:Import/Export . History can't be realistically produced.

If the wiki is less than a thousand pages big, it's probably easier to copy and paste pages one by one with the VisualEditor.

**Comment by trenkert** [comment]
thanks!
