### ISSUE TITLE
Wiki filenames with questionsmarks in them cause the wikidump generator script to fail. 

### ISSUE THREAD

**Issue by jefmeijvis** [WikiTeam/wikiteam#483]
A certain wiki had a file listed with the following name:
`Image:A generic name of an image?.png`

The following code `imagefile = open(filename3, 'wb')` at [dumpgenerator.py line 1494](https://github.com/WikiTeam/wikiteam/blob/master/dumpgenerator.py#L1494)  on a Windows filesystem throws an error saying that the filename is invalid. 

Would it be possible to replace question marks (and other characters that might need to be encoded) with variants that work on both Linux and Windows filesystems? 

Adding the following at line 1485 allowed the image download to continue.
However it still gave an error at the end because two files with a questionmark in their name couldn't be found in the wiki. (which makes sense ofcourse, because the following code renamed them)
```
        # Line 1485
        # Replace any question marks in the filename to guarantee filesystem compatibility.
        filename = filename.replace('?','questionmark')
```

**Comment by nemobis** [comment]
We don't support running dumpgenerator on a Windows filesystem, sorry. As this project is in the maintenance mode, I don't think we'll make such changes in the future.

**Comment by nemobis** [comment]
Our friends have forks at https://github.com/saveweb/wikiteam3 or https://github.com/mediawiki-client-tools/mediawiki-dump-generator which may or may not support your use case (I've not checked recently and I've not tried them, but I seem to recall some of them run the scripts under WSL).

**Comment by jefmeijvis** [comment]
Ok I'll have a look over there, thanks!
