### ISSUE TITLE
Rely on the internetarchive python package

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#54]
_From [ad...@alphacorp.tk](https://code.google.com/u/108738924166171172216/) on August 11, 2012 18:13:40_

Boto is a python package that is useful to upload files via the S3 API interface. It is much simpler and more reliable that the "hackish" curl command that we are using.

Note that most systems do not have this package installed by default in the python packages directory. We can instead put the directory containing the boto package files together with all our scripts and reference it when we call for boto to upload our dumps.

Not a major issue, as it does not hinder development for the dumpgenerator.py script, but instead helps in the uploader.py script that we currently have in trunk.

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=54_

**Comment by nemobis** [comment]
This was fixed in 2015 https://lists.wikimedia.org/pipermail/wikiapiary/2020-February/000039.html
