### ISSUE TITLE
commonsdownloader.py: try your.org first

### ISSUE THREAD

**Issue by emijrp** [WikiTeam/wikiteam#66]
_From [nemow...@gmail.com](https://code.google.com/u/101255742639286016490/) on October 03, 2013 18:34:21_

A WMF op kindly pointed out that their file backend is currently rather overloaded, so it would be nice to use your.org where possible and default to upload.wikimedia.org only when the files are missing there (currently, for sure anything after May 2013). http://ftpmirror.your.org/pub/wikimedia/images/wikipedia/commons/

_Original issue: http://code.google.com/p/wikiteam/issues/detail?id=66_

**Comment by Hydriz** [comment]
The Your.org mirror is hardly updated since 2013. This issue is probably outdated.
